### ISSUE TITLE
NPE when joining a game.

### ISSUE THREAD

**Issue by TheReverend403** [SpleefX/SpleefX#1]
**Server information**:
   * Paper
   * 1.15.1

**Exceptions  or  errors  in  console (if any)**: 

```
Jan 02 23:44:52 firefly.revthefox.co.uk minecraft[105132]: InstallGentoo issued server command: /spleef join simple_wood                                                                                            
Jan 02 23:45:02 firefly.revthefox.co.uk minecraft[105132]: [SpleefX] Task #3303 for SpleefX v2.2-SNAPSHOT generated an exception                                                                                    
Jan 02 23:45:02 firefly.revthefox.co.uk minecraft[105132]: java.lang.IllegalArgumentException: Material cannot be null                                                                                              
Jan 02 23:45:02 firefly.revthefox.co.uk minecraft[105132]:         at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[patched_1.15.1.jar:git-Paper-33]                                                
Jan 02 23:45:02 firefly.revthefox.co.uk minecraft[105132]:         at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:73) ~[patched_1.15.1.jar:git-Paper-33]                                                   
Jan 02 23:45:02 firefly.revthefox.co.uk minecraft[105132]:         at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:61) ~[patched_1.15.1.jar:git-Paper-33]                                                   
Jan 02 23:45:02 firefly.revthefox.co.uk minecraft[105132]:         at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:49) ~[patched_1.15.1.jar:git-Paper-33]                                                   
Jan 02 23:45:02 firefly.revthefox.co.uk minecraft[105132]:         at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:39) ~[patched_1.15.1.jar:git-Paper-33]                                                   
Jan 02 23:45:02 firefly.revthefox.co.uk minecraft[105132]:         at io.github.spleefx.extension.ItemHolder.factory(ItemHolder.java:69) ~[?:?]                                                                     
Jan 02 23:45:02 firefly.revthefox.co.uk minecraft[105132]:         at io.github.spleefx.arena.api.BaseArenaEngine.lambda$prepareForGame$11(BaseArenaEngine.java:367) ~[?:?]                                         
Jan 02 23:45:02 firefly.revthefox.co.uk minecraft[105132]:         at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684) ~[?:?]                                                                                
Jan 02 23:45:02 firefly.revthefox.co.uk minecraft[105132]:         at io.github.spleefx.arena.api.BaseArenaEngine.prepareForGame(BaseArenaEngine.java:367) ~[?:?]                                                   
Jan 02 23:45:02 firefly.revthefox.co.uk minecraft[105132]:         at io.github.spleefx.arena.api.BaseArenaEngine.lambda$start$15(BaseArenaEngine.java:430) ~[?:?]                                                  
Jan 02 23:45:02 firefly.revthefox.co.uk minecraft[105132]:         at java.util.HashMap.forEach(HashMap.java:1336) ~[?:?]                                                                                           
Jan 02 23:45:02 firefly.revthefox.co.uk minecraft[105132]:         at io.github.spleefx.arena.api.BaseArenaEngine.start(BaseArenaEngine.java:428) ~[?:?]                                                            
Jan 02 23:45:02 firefly.revthefox.co.uk minecraft[105132]:         at io.github.spleefx.arena.api.BaseArenaEngine.lambda$countdown$14(BaseArenaEngine.java:417) ~[?:?]                                              
Jan 02 23:45:02 firefly.revthefox.co.uk minecraft[105132]:         at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.1.jar:git-Paper-33]                                 
Jan 02 23:45:02 firefly.revthefox.co.uk minecraft[105132]:         at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.15.1.jar:git-Paper-33]      
Jan 02 23:45:02 firefly.revthefox.co.uk minecraft[105132]:         at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1179) ~[patched_1.15.1.jar:git-Paper-33]                                 
Jan 02 23:45:02 firefly.revthefox.co.uk minecraft[105132]:         at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.15.1.jar:git-Paper-33]                                  
Jan 02 23:45:02 firefly.revthefox.co.uk minecraft[105132]:         at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1106) ~[patched_1.15.1.jar:git-Paper-33]                                 
Jan 02 23:45:02 firefly.revthefox.co.uk minecraft[105132]:         at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:933) ~[patched_1.15.1.jar:git-Paper-33]                                
Jan 02 23:45:02 firefly.revthefox.co.uk minecraft[105132]:         at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by TheReverend403** [comment]
Fixed. Had to update DIAMOND_SPADE to DIAMOND_SHOVEL.
