### ISSUE TITLE
Players are kicked after the end of a match

### ISSUE THREAD

**Issue by TheoRetisch1** [SpleefX/SpleefX#1]
Since the update to version 1.19.3, players are kicked from the server after the end of a Spleef round as soon as the round summary should actually appear in their chat. The reason for the kick in the Minecraft client is `Chat validation failure`.

The following error appears in the log:
```
[15:23:39 WARN]: java.lang.IllegalStateException: Unsuccessful |
[15:23:39 WARN]: at SpleefX-4.9.5.jar//net.spleefx.backend.SpleefXWebAPI.lambda$createStats$0(SpleefXWebAPI.java:58) |
[15:23:39 WARN]: at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1375) |
[15:23:39 WARN]: at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) |
[15:23:39 WARN]: at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) |
[15:23:39 WARN]: at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) |
[15:23:39 WARN]: at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) |
[15:23:39 WARN]: at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) 
```

SpleefX version 4.9.5
git-Paper-307 (MC: 1.19.2)

**Comment by haytada** [comment]
I am getting the exact same error. I have asked in their discord only moments ago so fingers crossed for a response to see what's going on! Glad I'm not the only one.

**Comment by TheoRetisch1** [comment]
The problem still remains, unfortunately it has not been fixed.

**Comment by Revxrsal** [comment]
I have a drafted release which should include a fix for this, as well as full support for Minecraft 1.19 and 1.20+. It should be out in the upcoming week hopefully.

**Comment by Revxrsal** [comment]
Update released: [spigotmc.org/resources/73093](https://www.spigotmc.org/resources/73093/)
